name: Build & Publish Docker Image For aarch64

on:
  push:
    branches: ["master"]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            oddcc/my-code-server:latest

      - name: Push Docker image
        run: docker push oddcc/my-code-server:latest
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Update container on the server
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          private_key_filename: ${{ secrets.PRIVATE_KEY_FILENAME }}
          private_key_value: ${{ secrets.PRIVATE_KEY_VALUE }}
          port: ${{ secrets.SSH_PORT }}
          service_token_id: ${{ secrets.SERVICE_TOKEN_ID }}
          service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}
          commands: |
            cd ~/container/my-code-server
            git fetch origin main
            git reset --hard origin/main
            docker-compose pull
            docker-compose down
            docker-compose up -d

            while :; do
              LOG_OUTPUT=$(docker logs --tail=50 code-server)
              echo "$LOG_OUTPUT"
              if echo "$LOG_OUTPUT" | grep -F "info  Session server listening on"; then
                echo "Service started successfully."
                exit 0
              fi
              sleep 5
            done
